'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>  _
Partial Public NotInheritable Class AppDB
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As AppDB = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New AppDB()),AppDB)
    
    Public Shared ReadOnly Property [Default]() As AppDB
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("""BHATHRISH\SQLEXPRESS""")>  _
    Public ReadOnly Property LocalDB() As String
        Get
            Return CType(Me("LocalDB"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("""BHATHRISH\SQLEXPRESS""")>  _
    Public ReadOnly Property WebDB() As String
        Get
            Return CType(Me("WebDB"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("""Localuser""")>  _
    Public ReadOnly Property LocalDBUserName() As String
        Get
            Return CType(Me("LocalDBUserName"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("""Good_143""")>  _
    Public ReadOnly Property LocalDBPassword() As String
        Get
            Return CType(Me("LocalDBPassword"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("""WebUser""")>  _
    Public ReadOnly Property WebDBUserName() As String
        Get
            Return CType(Me("WebDBUserName"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("""Good_143""")>  _
    Public ReadOnly Property WebDBPassword() As String
        Get
            Return CType(Me("WebDBPassword"),String)
        End Get
    End Property
End Class
